Nathi discourse
KilnOfTheSecondFlame/InfKolThesis pull request #11
Opened 2017-05-09 21:23 UTC by NathDrac

Hi all

I have written A LOT, and my fingers and eyes are bleeding ;-) Please check, if this can be merged.

2017-05-10 06:57 UTC, KilnOfTheSecondFlame requested changes
Oh no - bleeding eyes are not good 😢 
But could you address my points, so that we are able to merge?

2017-05-10 06:57 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +Furthermore, however, the user is most often required to agree to software license agreements, stating further limitations to which the license of the software is subject to. This mechano is summariz
Either use "Furthermore" or "However" - Both together are unnecessary and cumbersome

2017-05-10 06:57 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +Furthermore, however, the user is most often required to agree to software license agreements, stating further limitations to which the license of the software is subject to. This mechano is summariz
'mechano' is a colloquialism, beter use: "This mechanism is summarized [...]"

2017-05-10 06:57 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +Furthermore, however, the user is most often required to agree to software license agreements, stating further limitations to which the license of the software is subject to. This mechano is summariz
Section 117 of what? The Licencing Act 2003? This: Application for grant or renewal of personal licence ?
If so, please specify, which right Section 117 would grant an End-User, before explaining what not applying means.

2017-05-10 06:57 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +	\item In the current age, music is often not the creation of an inspired artist but of composers creating goods based on market research, e.g. the current music taste and characterizations of idols
So what if the market is flooded with low quality music?
Or said differently: How does this relate to copyright?

2017-05-10 06:57 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +The author of this chapter is a firm believer in open source software. Innovation can no longer exist in a vacuum, because so many things already exist. And innovation is important for the advancemen
Google on the other hand would not have succeeded were it _not_ for OSS.

2017-05-10 06:57 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +The author of this chapter is a firm believer in open source software. Innovation can no longer exist in a vacuum, because so many things already exist. And innovation is important for the advancemen
Such a scenario is realistic, but _should_ not be.
At least that's what I think you meant =)

2017-05-10 06:57 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +The society should ask itself if it wants to cater to the needs of greedy corporations and believe their propaganda, or if not the need to solve problems would lead to the discoveries of things witho
Nice! 👍

2017-05-12 07:35 UTC, NathDrac commented on Thesis.tex
> +The author of this chapter is a firm believer in open source software. Innovation can no longer exist in a vacuum, because so many things already exist. And innovation is important for the advancemen
I changed it. but I really meant "dies darf nicht der fall sein" - habe aber deine Abschwächung akzeptiert, da es ja so offentsischtlich aktuell der Fall ist.

2017-05-12 08:10 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +The author of this chapter is a firm believer in open source software. Innovation can no longer exist in a vacuum, because so many things already exist. And innovation is important for the advancemen
Jop, das habe ich eigentlich damit gemeint, aber gebe dir recht "das darf nicht der Fall sein"

2017-05-12 08:41 UTC, KilnOfTheSecondFlame approved these changes

2017-05-12 08:41 UTC, merged