Chapter about Copright
KilnOfTheSecondFlame/InfKolThesis pull request #3
Opened 2017-03-22 13:41 UTC by PixelSupreme

2017-03-26 13:38 UTC, KilnOfTheSecondFlame requested changes

2017-03-26 13:38 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +According to the berne convention copyright is obtained automatically with the act of creation and usually covers a very long time span. There is no registration needed before one can claim and enfor
Berne Convention should be capitalised, as it is a name

2017-03-26 13:38 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +Probably the most common misunderstanding is that everything found on the internet can be freely downloaded and used as the basis of own works. However this is nit true in most cases. As mentioned in
'However this is _not_ true'

2017-03-26 13:38 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +Probably the most common misunderstanding is that everything found on the internet can be freely downloaded and used as the basis of own works. However this is nit true in most cases. As mentioned in
wether you payed for _it_ or not

2017-03-26 13:38 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +Another very common misconception often seen on YouTube is that it suffices to either give credit to the original creator, add a copyright notice or claim so called fair use. Adding a copyright notic
_Proper_ authorization to use the work is still required

2017-03-27 20:39 UTC, NathDrac commented on Thesis.tex
> +Copyright is a form of intellectual property right generally associated with works of artistic value. It is intended to fight plagiarism. The legal term copyright describes the rights a creator holds
citation needed

2017-03-27 20:40 UTC, NathDrac commented on Thesis.tex
> +Copyright is a form of intellectual property right generally associated with works of artistic value. It is intended to fight plagiarism. The legal term copyright describes the rights a creator holds
Vielleicht auf den ursprung hinweisen: Rechte am Werk und dieses zu kopieren, soweit ich weiss? Wiederum: Quelle benennen

2017-03-27 20:41 UTC, NathDrac commented on Thesis.tex
> +Copyright usually only applies to a practical expression and not ideas, procedures or mode of operation. Copyright includes economical and moral rights. The economical rights allow the rights holder
Quelle fehlt

2017-03-27 20:42 UTC, NathDrac commented on Thesis.tex
> +According to the berne convention copyright is obtained automatically with the act of creation and usually covers a very long time span. There is no registration needed before one can claim and enfor
berne convention, copyright is ...

Quelle....

2017-03-27 20:47 UTC, NathDrac commented on Thesis.tex
> +Probably the most common misunderstanding is that everything found on the internet can be freely downloaded and used as the basis of own works. However this is nit true in most cases. As mentioned in
However, this is not true...

Du verweist auf vorys et al - klarstellen, welche Aussage dort gemacht wird? Ich nehme an es betrifft die Aussage "Probably the most..." ?

unlicensed reuse is prohibited unless explicitly authorized by the rights owner: ist diese Authorisierung nicht per se eine Lizenz, womit es nicht mehr unlicensed reuse ist?

Wheter you paid for it or not

2017-03-27 20:52 UTC, NathDrac commented on Thesis.tex
> +Another very common misconception often seen on YouTube is that it suffices to either give credit to the original creator, add a copyright notice or claim so called fair use. Adding a copyright notic
Woher hast Du diese misconception? auch von vorys?

Claim fair use: Dies IST eine valide Möglichkeit der Verteidigung. Im Gegenteil ist es eher so, dass die Gerichte im Falle von Fair Use eher für die Angeklagten entscheiden als für die Rechteinhaber, welche das Thema lieber ganz weglassen würden ... aber auch hier brauachts noch ne Quelle

Adding a copyright notice or crediting the original author has no legal meaning by itself - hier vielleicht noch ergänzen, dass dies im Falle von Creative Commons oftmals wirklich genügt, allerdings wird durch CC eine Lizenz erteilt unter der Auflage, dass der Author genannt wird. Hier könnte man präzisieren.

Proper authorization : P fehlt...

2017-03-27 21:07 UTC, NathDrac commented on Thesis.tex
> +The aforementioned fair use is also a source for confusion among internet users. Fair use is a doctrine that under certain circumstances allows the use of copyrighted material without acquiring permi
Stimmt so nicht ganz. Es ist zwar eine defense (mit s geschrieben). Zwar muss das Gericht Fall für Fall beurteilen, 

In Lenz v. Universal Music Group wird ersichtlich, dass Fair Use nicht nur ein "erlaubter Verstoss" sondern dass es sich um erlaubte Aktionen handelt:

Here, the Court concludes that the plain meaning of "authorized by law" is unambiguous. An activity or behavior "authorized by law" is one permitted by law or not contrary to law. Though Congress did not expressly mention the fair use doctrine in the DMCA, the Copyright Act provides explicitly that "the fair use of a copyrighted work ... is not an infringement of copyright."   https://h2o.law.harvard.edu/cases/5589

Weiterhin ist es so, dass im Falle eines Gerichtsprozesses das Gericht entscheiden muss, auch hier gibt es aber Vorgaben, so, aus dem Selben Urteil

The Copyright Act unequivocally establishes the four factors used to determine fair use:

    In determining whether the use made of a work in any particular case is a fair use the factors to be considered shall include—

    (1) the purpose and character of the use, including whether such use is of a commercial nature or is for nonprofit educational purposes;

    (2) the nature of the copyrighted work;

    (3) the amount and substantiality of the portion used in relation to the copyrighted work as a whole; and

    (4) the effect of the use upon the potential market for or value of the copyrighted work.

The fact that a work is unpublished shall not itself bar a finding of fair use if such finding is made upon consideration of all the above factors.

Es stimmt, dass im legalen Sinne eine description mit Hinweis auf Fair Use nicht genügt. Allerdings wäre es die Pflicht der Rechteinhaber vor einer Abmahnung, DMCA oder ähnlichem die Anwendbarkeit von Fair Use prüfen müssten (steht irgendwo im gleichen lenz vs UMG Urteil

2017-03-27 21:09 UTC, NathDrac commented on Thesis.tex
> +The aforementioned fair use is also a source for confusion among internet users. Fair use is a doctrine that under certain circumstances allows the use of copyrighted material without acquiring permi
Gesamthaft scheinst Du mir zuviele Quellen der Lobbies und zuwenige aus der Praxis zuhilfe genommen zu haben. Meine Sicht auf Copyrights ist vielem diagonal entgegenstehend, und zwar basierend auf Gerichtsentscheiden etc...

2017-03-28 05:01 UTC, merged