Current situation first version
KilnOfTheSecondFlame/InfKolThesis pull request #7
Opened 2017-04-04 19:32 UTC by PixelSupreme

2017-04-10 15:03 UTC, KilnOfTheSecondFlame requested changes

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +The global development of industries over the past few decades had quite a significant impact related to patents. More companies from all over the world hold patents relevant to sometimes whole indus
Companies from all over the world _sometimes_ hold patents relevant to whole industry branches.

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +The global development of industries over the past few decades had quite a significant impact related to patents. More companies from all over the world hold patents relevant to sometimes whole indus
Furthermore, the number of _licensed_ patents _used_ in modern products and services _has taken on a whole new dimension_.

I'm actually not a hundred percent sure if "take on a new dimension" is used correctly in this context. I will ask my english professor on wednesday.

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +The global development of industries over the past few decades had quite a significant impact related to patents. More companies from all over the world hold patents relevant to sometimes whole indus
One example for this is the LTE standard for mobile communcations: Differing opinions and a multitude of affected patents belonging to different technology companies, led to several law suits between these parties and a delay of years until the adaption of this standard.

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +As technology gets more complex, more companies are involved in development of individual elements that make up standards, services and products of our modern age. And since new technologies are ofte
And, since new [...] established ones, it is no surprise, that some modern products are related to an astounding numbers of patents.

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +As technology gets more complex, more companies are involved in development of individual elements that make up standards, services and products of our modern age. And since new technologies are ofte
As an example, we take a look at the 3GPP mobile communications standard.

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +As technology gets more complex, more companies are involved in development of individual elements that make up standards, services and products of our modern age. And since new technologies are ofte
It is clear, that with such large pools of patents relevant to industry standards, proper licensing is a complex matter.

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +The follow-up standard LTE is also no exception. While it is not easy to find exact numbers on the size of the patent pool related to the standard, its effects were rather visible over the past few y
The follow-up standard LTE is no exception _either_.

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +The follow-up standard LTE is also no exception. While it is not easy to find exact numbers on the size of the patent pool related to the standard, its effects were rather visible over the past few y
[...] and Huawei versus T-Mobile, _just to name a few_.

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +To limit the risk of patent infringement lawsuits many companies enter cross-licensing agreements. Parties involved in a cross-licensing agreement grant each other a license to exploit patents relate
To limit the risk of patent infringement lawsuits, many companies enter cross-licensing agreements.

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +A main limitation of cross licensing is that it is ineffective against patent holding companies. Their primary business model is to acquire and license patents for monetary royalty. As such hey have
Their primary business model is to acquire patents, _and exploit these for monetary royalties_.

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +A main limitation of cross licensing is that it is ineffective against patent holding companies. Their primary business model is to acquire and license patents for monetary royalty. As such hey have
_Thus, they_ have no _benefit in obtaining_ the rights to _use_ other companies' patents.

2017-04-10 15:03 UTC, KilnOfTheSecondFlame commented on Thesis.tex
> +This refers to a voluntary licensing commitment often requested by standards organisations from holders of patents that might become essential to a technical standard. Fair relates to the underlying
Reasonable refers to the _height_ of license rates.

2017-04-12 08:10 UTC, NathDrac commented on Thesis.tex
> +The global development of industries over the past few decades had quite a significant impact related to patents. More companies from all over the world hold patents relevant to sometimes whole indus
<<<< Differing opinions and a multitude of affected patents belonging to different technology **companies led** to several law suits between these parties and a delay of years until the adaption of this standard.

2017-04-12 08:15 UTC, NathDrac commented on Thesis.tex
> +As technology gets more complex, more companies are involved in development of individual elements that make up standards, services and products of our modern age. And since new technologies are ofte
Also ich würde kein komma nach clear setzen, aber ganz klar eins vor proper

2017-04-12 08:17 UTC, NathDrac commented on Thesis.tex
> +To limit the risk of patent infringement lawsuits many companies enter cross-licensing agreements. Parties involved in a cross-licensing agreement grant each other a license to exploit patents relate
Ich würde hier use patents verwenden anstelle exploit patents. Exploit hat definitiv in der Mehrzahl der Bedeutungen einen negativ wertenden Beigeschmack

2017-04-12 08:19 UTC, NathDrac commented on Thesis.tex
> +A main limitation of cross licensing is that it is ineffective against patent holding companies. Their primary business model is to acquire and license patents for monetary royalty. As such hey have
patent holding companies ist denke ich nicht der richtige Begriff, es sind die NPE (Non Practicing Entities), welche Patente halten, ohne sie selber zu verwenden.

2017-04-12 08:21 UTC, NathDrac commented on Thesis.tex
> +To manage the sheer magnitude of patents involved in modern standards, a licensing scheme based on reasonable, non-discriminatory terms (sometimes also fair, reasonable and non-discriminator terms) h
(sometimes also fair, reasonable and non-discriminator**y** terms)

2017-04-12 08:22 UTC, NathDrac commented on Thesis.tex
> +This refers to a voluntary licensing commitment often requested by standards organisations from holders of patents that might become essential to a technical standard. Fair relates to the underlying
As the name suggest**s,** it means

2017-04-12 08:23 UTC, NathDrac commented on Thesis.tex
> +Another important case related to RAND is Microsoft versus Motorola. In 2012 the United States Court of Appeals for the Ninth Circuit ruled that a patent holder's agreement to a policy like RAND crea
In 2012**,** the United States Court of Appeals

2017-04-12 08:24 UTC, NathDrac commented on Thesis.tex
> +Another important case related to RAND is Microsoft versus Motorola. In 2012 the United States Court of Appeals for the Ninth Circuit ruled that a patent holder's agreement to a policy like RAND crea
Scheint mir sehr gut recherchiert!

2017-04-12 18:06 UTC, KilnOfTheSecondFlame approved these changes

2017-04-12 18:11 UTC, merged